apiVersion: v1
kind: Service
metadata:
  name: spark-metrics
  labels:
    app: spark
spec:
  selector:
    app-role: spark-executor
  ports:
    - name: metrics
      port: 9404
      targetPort: 9404
