apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: spark-metrics
  namespace: monitoring
spec:
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - spark
          - spark-worker
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - port: metrics
      interval: 10s