apiVersion: batch/v1
kind: Job
metadata:
  name: spark-job
spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: spark
          image: jonathan/spark-app:1.5
          imagePullPolicy: IfNotPresent
          command:
            - /opt/spark/bin/spark-submit
            - /opt/spark/app.py
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: spark-data-pvc
