{
 "title": "Spark KEDA Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Executor lifecycle",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{pod=~\"spark-worker-keda.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Executor count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(up{pod=~\"spark-worker-keda.*\"})",
     "legendFormat": "Executors"
    }
   ]
  },
  {
   "title": "CPU usage per executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "CPU seconds / second" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{pod=~\"spark-worker-keda.*\"}[30s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\", pod=~\"spark-worker-keda.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}